# Generated by Django 5.2.4 on 2025-09-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mini_catalog', '0005_remove_order_is_completed_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
