# Generated by Django 5.2.4 on 2025-09-11 01:43

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mini_catalog', '0007_order_proof_of_payment_completedorder_rejectedorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedorder',
            name='proof_of_payment',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/proofs'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='proof_of_payment',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/proofs'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='rejectedorder',
            name='proof_of_payment',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/proofs'), upload_to=''),
        ),
    ]
