# Generated by Django 5.2.4 on 2025-10-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mini_catalog', '0013_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Average rating out of 5', max_digits=3),
        ),
    ]
