# Generated by Django 5.2.4 on 2025-11-03 13:19

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mini_catalog', '0014_product_num_ratings_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedorder',
            name='proof_of_payment',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='proof_of_payment',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='rejectedorder',
            name='proof_of_payment',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media'), upload_to=''),
        ),
    ]
